### ISSUE TITLE
Keyword: TOML

### ISSUE THREAD

**Issue by EloiStree** [EloiStree/HelloSharpForUnity3D#502]
https://toml.io/en/

-----------------

# 🤖 cheat sheet

## **Basic Structure**
```toml
# Comments start with #
title = "TOML Example"
```

---

### **Strings**
```toml
string = "Hello, World!"
multiline = """This is 
a multiline string."""
```

### **Numbers**
```toml
integer = 42
float = 3.14
```

### **Boolean**
```toml
is_enabled = true
is_disabled = false
```

### **Date/Time**
```toml
datetime = 2024-02-02T12:34:56Z  # UTC
datetime_offset = 2024-02-02T12:34:56-05:00  # With offset
```

---

## **Arrays**
```toml
numbers = [1, 2, 3]
strings = ["apple", "banana", "cherry"]
```

### **Nested Arrays**
```toml
matrix = [[1, 2], [3, 4]]
```

---

## **Tables (Objects)**
```toml
[person]
name = "Alice"
age = 30
```

### **Nested Tables**
```toml
[person.address]
city = "New York"
zipcode = "10001"
```

---

## **Arrays of Tables (List of Objects)**
```toml
[[employees]]
name = "John"
age = 25

[[employees]]
name = "Jane"
age = 30
```

---

## **Inline Tables**
```toml
user = { name = "Bob", age = 40 }
```

---

## **Multi-Line Arrays**
```toml
fruits = [
    "apple",
    "banana",
    "cherry"
]
```

---

This covers the key aspects of TOML. Let me know if you need more details! 🚀
